CREATE TABLE users
(
    id SERIAL PRIMARY KEY,
    username VARCHAR(30) UNIQUE NOT NULL,
    fname VARCHAR(30) NOT NULL,
    lname VARCHAR(30) NOT NULL,
    email VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    exp INTEGER,
    total_books INTEGER,
    total_pages INTEGER
);

CREATE TABLE reads
(
    id SERIAL PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    description VARCHAR(500),
    isbn VARCHAR(20),
    avg_rating INTEGER,
    print_type VARCHAR(20),
    publisher VARCHAR(50)
);

CREATE TABLE collections
(
    id SERIAL PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    user_id INTEGER NOT NULL REFERENCES users ON DELETE CASCADE
);

CREATE TABLE badges
(
    id SERIAL PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    thumbnail VARCHAR(30) NOT NULL
);

CREATE TABLE users_reads
(
    id SERIAL PRIMARY KEY,
    rating INTEGER,
    review_text VARCHAR(7500),
    review_date DATE,
    user_id INTEGER NOT NULL REFERENCES users ON DELETE CASCADE,
    read_id INTEGER NOT NULL REFERENCES reads ON DELETE CASCADE
);

CREATE TABLE authors
(
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE users_badges
(
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users ON DELETE CASCADE,
    badge_id INTEGER NOT NULL REFERENCES badges ON DELETE CASCADE
);

CREATE TABLE reads_collections
(
    id SERIAL PRIMARY KEY,
    read_id INTEGER NOT NULL REFERENCES reads ON DELETE CASCADE,
    collection_id INTEGER NOT NULL REFERENCES collections ON DELETE CASCADE
);

CREATE TABLE reads_authors
(
    id SERIAL PRIMARY KEY,
    read_id INTEGER NOT NULL REFERENCES reads ON DELETE CASCADE,
    author_id INTEGER NOT NULL REFERENCES authors ON DELETE CASCADE
);

CREATE TABLE journals
(
    id SERIAL PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    date DATE NOT NULL,
    text VARCHAR(7500),
    user_id INTEGER NOT NULL REFERENCES users ON DELETE CASCADE
);

CREATE TABLE users_followed
(
    id SERIAL PRIMARY KEY,
    followed_id INTEGER UNIQUE NOT NULL REFERENCES users ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users ON DELETE CASCADE
);

CREATE TABLE users_followers
(
    id SERIAL PRIMARY KEY,
    follower_id INTEGER UNIQUE NOT NULL REFERENCES users ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users ON DELETE CASCADE
);

CREATE TABLE recommendations
(
    id SERIAL PRIMARY KEY,
    recommendation VARCHAR(1000) NOT NULL,
    receiver_id INTEGER NOT NULL REFERENCES users ON DELETE CASCADE,
    sender_id INTEGER NOT NULL REFERENCES users ON DELETE CASCADE
);